spring:
  application:
    name: health

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shec_psims
    username: root
    password: 2004

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  servlet:
    multipart:
          enabled: true
          max-file-size: 20MB # 设置最大文件大小，例如 10MB
          max-request-size: 20MB # 设置最大请求大小，例如 10MB
          location: uploads/ # 设置上传文件的存储目录
  mvc:
    static-path-pattern: /admin/goods/static/**
  web:
    resources:
      static-locations: file:C:/image/




mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.webtab.shecpsims.model.entity
  mapper-locations: classpath:com.webtab.shecpsims.mapper/*

